
check1:
	@echo '------------------------- QUESTION 1 ------------------------------'
	@cd question1 && make check

check3:
	@echo '------------------------- QUESTION 3 ------------------------------'
	@cd question3 && make check

check4:
	@echo '------------------------- QUESTION 4 ------------------------------'
	@cd question4 && make check

check_all: check1 check3 check4
	@echo '-------------------------------------------------------------------'
	@echo 'Checks finished!'
