
check1:
	@echo '------------------------- QUESTION 1 ------------------------------'
	@cd question1 && make check

check2:
	@echo '------------------------- QUESTION 2 ------------------------------'
	@cd question2 && make check

check3:
	@echo '------------------------- QUESTION 3 ------------------------------'
	@cd question3 && make check

check_all: check1 check2 check3
	@echo '-------------------------------------------------------------------'
	@echo 'Checks finished!'
